class_name BiomeDefs
extends RefCounted

const SYSTEM: Dictionary = {
	"plains": {
		"biome_id": "plains", "kind": "biome", "schema_version": "1.0", "catalog_revision": 0,
		"display": {"name": {"en": "Plains"}, "description": {"en": "Open grassland with occasional trees."}},
		"visual": {"sky_color": "#67b8e3", "daylight_tint": "#fff7df"},
		"terrain": {"surface_content_id": "core.grass", "subsurface_content_id": "core.dirt", "deep_content_id": "core.stone", "fluid_content_id": null},
		"ecology": {"plant_content_ids": ["core.plant.meadow_bloom", "core.plant.prairie_sprig", "core.plant.oak", "core.plant.weeping_tree"], "creature_content_ids": ["core.creature.meadow_hopper", "core.creature.forest_fox", "core.creature.sky_mote", "core.creature.firefly", "core.creature.watcher_bloom", "core.creature.dusk_prowler"]},
		"environment": {"temperature": 0.2, "rain_multiplier": 1.0, "daylight_multiplier": 1.0},
		"placement": {"minimum_chunk_distance": 0, "introduction_chance": 1.0, "maximum_chunks_per_region": 8},
		"source_content_ids": ["core.grass", "core.dirt", "core.stone"],
	},
	"forest": {
		"biome_id": "forest", "kind": "biome", "schema_version": "1.0", "catalog_revision": 0,
		"display": {"name": {"en": "Forest"}, "description": {"en": "A damp woodland rich in trees and small creatures."}},
		"visual": {"sky_color": "#63add0", "daylight_tint": "#e5f4d4"},
		"terrain": {"surface_content_id": "core.grass", "subsurface_content_id": "core.dirt", "deep_content_id": "core.stone", "fluid_content_id": null},
		"ecology": {"plant_content_ids": ["core.plant.prairie_sprig", "core.plant.meadow_bloom", "core.plant.oak", "core.plant.weeping_tree"], "creature_content_ids": ["core.creature.meadow_hopper", "core.creature.forest_fox", "core.creature.moss_crawler", "core.creature.moss_slug", "core.creature.cave_spider", "core.creature.sky_mote", "core.creature.firefly", "core.creature.watcher_bloom", "core.creature.dusk_prowler", "core.creature.gloomwing"]},
		"environment": {"temperature": 0.05, "rain_multiplier": 1.35, "daylight_multiplier": 0.88},
		"placement": {"minimum_chunk_distance": 1, "introduction_chance": 1.0, "maximum_chunks_per_region": 8},
		"source_content_ids": ["core.grass", "core.dirt", "core.stone", "core.wood"],
	},
	"crystal_grove": {
		"biome_id": "crystal_grove", "kind": "biome", "schema_version": "1.0", "catalog_revision": 0,
		"display": {"name": {"en": "Crystal Grove"}, "description": {"en": "Lavender grasslands where rose and amethyst crystals reach the surface."}},
		"visual": {"sky_color": "#9f83d9", "daylight_tint": "#ffe0f5"},
		"terrain": {"surface_content_id": "core.grass", "subsurface_content_id": "core.dirt", "deep_content_id": "core.stone", "fluid_content_id": null},
		"ecology": {"plant_content_ids": ["core.plant.meadow_bloom", "core.plant.prairie_sprig", "core.plant.weeping_tree"], "creature_content_ids": ["core.creature.prism_moth", "core.creature.sky_mote", "core.creature.firefly", "core.creature.watcher_bloom", "core.creature.gloomwing"]},
		"environment": {"temperature": 0.1, "rain_multiplier": 0.9, "daylight_multiplier": 0.92},
		"placement": {"minimum_chunk_distance": 3, "introduction_chance": 1.0, "maximum_chunks_per_region": 8},
		"source_content_ids": ["core.grass", "core.dirt", "core.stone", "core.rose_crystal", "core.amethyst_crystal"],
	},
	"tundra": {
		"biome_id": "tundra", "kind": "biome", "schema_version": "1.0", "catalog_revision": 0,
		"display": {"name": {"en": "Tundra"}, "description": {"en": "A cold open land where water slowly freezes."}},
		"visual": {"sky_color": "#9fc9dc", "daylight_tint": "#e8f7ff"},
		"terrain": {"surface_content_id": "core.dirt", "subsurface_content_id": "core.dirt", "deep_content_id": "core.stone", "fluid_content_id": null},
		"ecology": {"plant_content_ids": ["core.plant.pine"], "creature_content_ids": ["core.creature.snow_penguin", "core.creature.sky_mote", "core.creature.gloomwing"]},
		"environment": {"temperature": -0.75, "rain_multiplier": 0.65, "daylight_multiplier": 0.82},
		"placement": {"minimum_chunk_distance": 4, "introduction_chance": 1.0, "maximum_chunks_per_region": 8},
		"source_content_ids": ["core.dirt", "core.stone", "core.ice"],
	},
	"ice": {
		"biome_id": "ice", "kind": "biome", "schema_version": "1.0", "catalog_revision": 0,
		"display": {"name": {"en": "Ice Fields"}, "description": {"en": "A barren glacier of deep ice, frozen water, and exposed stone."}},
		"visual": {"sky_color": "#b9dced", "daylight_tint": "#dff6ff"},
		"terrain": {"surface_content_id": "core.ice", "subsurface_content_id": "core.ice", "deep_content_id": "core.stone", "fluid_content_id": "core.water"},
		"ecology": {"plant_content_ids": [], "creature_content_ids": ["core.creature.snow_penguin", "core.creature.sky_mote", "core.creature.gloomwing"]},
		"environment": {"temperature": -0.95, "rain_multiplier": 0.35, "daylight_multiplier": 0.76},
		"placement": {"minimum_chunk_distance": 0, "introduction_chance": 1.0, "maximum_chunks_per_region": 8},
		"source_content_ids": ["core.ice", "core.stone", "core.water"],
	},
	"desert": {
		"biome_id": "desert", "kind": "biome", "schema_version": "1.0", "catalog_revision": 0,
		"display": {"name": {"en": "Desert"}, "description": {"en": "Dry dunes over deep stone."}},
		"visual": {"sky_color": "#77c6e8", "daylight_tint": "#ffe6ad"},
		"terrain": {"surface_content_id": "core.sand", "subsurface_content_id": "core.sand", "deep_content_id": "core.stone", "fluid_content_id": null},
		"ecology": {"plant_content_ids": [], "creature_content_ids": ["core.creature.sky_mote", "core.creature.dusk_prowler"]},
		"environment": {"temperature": 0.85, "rain_multiplier": 0.25, "daylight_multiplier": 1.12},
		"placement": {"minimum_chunk_distance": 2, "introduction_chance": 1.0, "maximum_chunks_per_region": 8},
		"source_content_ids": ["core.sand", "core.stone"],
	},
	"obsidian": {
		"biome_id": "obsidian", "kind": "biome", "schema_version": "1.0", "catalog_revision": 0,
		"display": {"name": {"en": "Obsidian Wastes"}, "description": {"en": "Weathered volcanic ground hiding deep obsidian, ancient formations, and lava pools."}},
		"visual": {"sky_color": "#59476d", "daylight_tint": "#d5b4df"},
		"terrain": {"surface_content_id": "core.cobblestone", "subsurface_content_id": "core.stone", "deep_content_id": "core.obsidian", "fluid_content_id": "core.lava"},
		"ecology": {"plant_content_ids": [], "creature_content_ids": ["core.creature.ember_walker", "core.creature.cinder_eel", "core.creature.gloomwing"]},
		"environment": {"temperature": 0.72, "rain_multiplier": 0.15, "daylight_multiplier": 0.78},
		"placement": {"minimum_chunk_distance": 0, "introduction_chance": 1.0, "maximum_chunks_per_region": 8},
		"source_content_ids": ["core.cobblestone", "core.stone", "core.obsidian", "core.lava"],
	},
	"beach": {
		"biome_id": "beach", "kind": "biome", "schema_version": "1.0", "catalog_revision": 0,
		"display": {"name": {"en": "Beach"}, "description": {"en": "A warm sandy edge beside open water."}},
		"visual": {"sky_color": "#72c8eb", "daylight_tint": "#fff1bd"},
		"terrain": {"surface_content_id": "core.sand", "subsurface_content_id": "core.sand", "deep_content_id": "core.stone", "fluid_content_id": "core.water"},
		"ecology": {"plant_content_ids": ["core.plant.palm"], "creature_content_ids": ["core.creature.pool_drifter", "core.creature.sand_crab", "core.creature.sky_mote"]},
		"environment": {"temperature": 0.55, "rain_multiplier": 0.8, "daylight_multiplier": 1.08},
		"placement": {"minimum_chunk_distance": 3, "introduction_chance": 1.0, "maximum_chunks_per_region": 8},
		"source_content_ids": ["core.sand", "core.stone", "core.water"],
	},
	"riverbank": {
		"biome_id": "riverbank", "kind": "biome", "schema_version": "1.0", "catalog_revision": 0,
		"display": {"name": {"en": "Riverbank"}, "description": {"en": "Low sandy ground shaped by flowing water."}},
		"visual": {"sky_color": "#69bce5", "daylight_tint": "#e8f8ff"},
		"terrain": {"surface_content_id": "core.sand", "subsurface_content_id": "core.sand", "deep_content_id": "core.stone", "fluid_content_id": "core.water"},
		"ecology": {"plant_content_ids": [], "creature_content_ids": ["core.creature.pool_drifter", "core.creature.sand_crab", "core.creature.moss_slug", "core.creature.sky_mote"]},
		"environment": {"temperature": 0.1, "rain_multiplier": 1.5, "daylight_multiplier": 0.98},
		"placement": {"minimum_chunk_distance": 2, "introduction_chance": 1.0, "maximum_chunks_per_region": 8},
		"source_content_ids": ["core.sand", "core.stone", "core.water"],
	},
	"cavern": {
		"biome_id": "cavern", "kind": "biome", "schema_version": "1.0", "catalog_revision": 0,
		"display": {"name": {"en": "Cavern"}, "description": {"en": "A dark underground habitat."}},
		"visual": {"sky_color": "#182439", "daylight_tint": "#7d89a0"},
		"terrain": {"surface_content_id": "core.stone", "subsurface_content_id": "core.stone", "deep_content_id": "core.stone", "fluid_content_id": null},
		"ecology": {"plant_content_ids": ["core.plant.cave_vines", "core.plant.luminous_moss"], "creature_content_ids": ["core.creature.geode_crawler", "core.creature.cave_spider", "core.creature.cave_skitter", "core.creature.moss_crawler", "core.creature.firefly", "core.creature.gloomwing"]},
		"environment": {"temperature": -0.15, "rain_multiplier": 0.0, "daylight_multiplier": 0.5},
		"placement": {"minimum_chunk_distance": 3, "introduction_chance": 1.0, "maximum_chunks_per_region": 8},
		"source_content_ids": ["core.stone"],
	},
	"volcanic": {
		"biome_id": "volcanic", "kind": "biome", "schema_version": "1.0", "catalog_revision": 0,
		"display": {"name": {"en": "Volcanic"}, "description": {"en": "Hot rock pockets inhabited by ember creatures."}},
		"visual": {"sky_color": "#7c514d", "daylight_tint": "#ffb06c"},
		"terrain": {"surface_content_id": "core.stone", "subsurface_content_id": "core.stone", "deep_content_id": "core.obsidian", "fluid_content_id": "core.lava"},
		"ecology": {"plant_content_ids": [], "creature_content_ids": ["core.creature.ember_walker", "core.creature.cinder_eel"]},
		"environment": {"temperature": 1.0, "rain_multiplier": 0.1, "daylight_multiplier": 0.8},
		"placement": {"minimum_chunk_distance": 6, "introduction_chance": 1.0, "maximum_chunks_per_region": 8},
		"source_content_ids": ["core.stone", "core.obsidian", "core.lava"],
	},
	"lumenroot_groves": {
		"biome_id": "lumenroot_groves", "kind": "biome", "schema_version": "1.0", "catalog_revision": 0,
		"display": {"name": {"en": "Lumenroot Groves"}, "description": {"en": "Living roots turn light into pathways and shelter far below the surface."}},
		"visual": {"sky_color": "#101f24", "daylight_tint": "#b8ffd0"},
		"terrain": {"surface_content_id": "core.lumenroot", "subsurface_content_id": "core.magnetic_stone", "deep_content_id": "core.magnetic_stone", "fluid_content_id": null},
		"ecology": {"plant_content_ids": ["core.plant.luminous_moss", "core.plant.cave_vines"], "creature_content_ids": ["core.creature.rootback_grazer"]},
		"environment": {"temperature": 0.05, "rain_multiplier": 0.0, "daylight_multiplier": 0.48},
		"placement": {"minimum_chunk_distance": 0, "introduction_chance": 1.0, "maximum_chunks_per_region": 8},
		"source_content_ids": ["core.lumenroot", "core.magnetic_stone", "core.resonance_bricks"],
	},
	"glass_tide_caverns": {
		"biome_id": "glass_tide_caverns", "kind": "biome", "schema_version": "1.0", "catalog_revision": 0,
		"display": {"name": {"en": "Glass-Tide Caverns"}, "description": {"en": "Crystalline currents can be routed, cooled, and crossed."}},
		"visual": {"sky_color": "#142838", "daylight_tint": "#c5f5ff"},
		"terrain": {"surface_content_id": "core.glass_tide_silt", "subsurface_content_id": "core.glass_tide_silt", "deep_content_id": "core.glass_tide_silt", "fluid_content_id": "core.glass_tide"},
		"ecology": {"plant_content_ids": ["core.plant.luminous_moss"], "creature_content_ids": ["core.creature.glasswing_ray"]},
		"environment": {"temperature": -0.2, "rain_multiplier": 0.0, "daylight_multiplier": 0.42},
		"placement": {"minimum_chunk_distance": 0, "introduction_chance": 1.0, "maximum_chunks_per_region": 8},
		"source_content_ids": ["core.glass_tide", "core.glass_tide_silt", "core.moonstone_ore"],
	},
	"prism_chasm": {
		"biome_id": "prism_chasm", "kind": "biome", "schema_version": "1.0", "catalog_revision": 0,
		"display": {"name": {"en": "Prism Chasm"}, "description": {"en": "Natural crystal fans split the cavern's ambient light into shifting colors."}},
		"visual": {"sky_color": "#271b3d", "daylight_tint": "#efc9ff"},
		"terrain": {"surface_content_id": "core.prismatic_basalt", "subsurface_content_id": "core.prismatic_basalt", "deep_content_id": "core.prismatic_basalt", "fluid_content_id": null},
		"ecology": {"plant_content_ids": [], "creature_content_ids": ["core.creature.prism_skitter"]},
		"environment": {"temperature": -0.05, "rain_multiplier": 0.0, "daylight_multiplier": 0.44},
		"placement": {"minimum_chunk_distance": 0, "introduction_chance": 1.0, "maximum_chunks_per_region": 8},
		"source_content_ids": ["core.prismatic_basalt", "core.amethyst_crystal", "core.rose_crystal", "core.emerald_crystal"],
	},
	"magnetic_ruins": {
		"biome_id": "magnetic_ruins", "kind": "biome", "schema_version": "1.0", "catalog_revision": 0,
		"display": {"name": {"en": "Shagot Enclave"}, "description": {"en": "Shagots mine natural lodestone and assemble open workshops around the old masonry."}},
		"visual": {"sky_color": "#211c31", "daylight_tint": "#e3c4ff"},
		"terrain": {"surface_content_id": "core.resonance_bricks", "subsurface_content_id": "core.magnetic_stone", "deep_content_id": "core.magnetic_stone", "fluid_content_id": null},
		"ecology": {"plant_content_ids": ["core.plant.luminous_moss"], "creature_content_ids": ["core.creature.shagot_wanderer", "core.creature.shagot_guide", "core.creature.shagot_raider"]},
		"environment": {"temperature": 0.12, "rain_multiplier": 0.0, "daylight_multiplier": 0.4},
		"placement": {"minimum_chunk_distance": 0, "introduction_chance": 1.0, "maximum_chunks_per_region": 8},
		"source_content_ids": ["core.magnetic_stone", "core.resonance_bricks", "core.lumenroot"],
	},
	"chorus_river": {
		"biome_id": "chorus_river", "kind": "biome", "schema_version": "1.0", "catalog_revision": 0,
		"display": {"name": {"en": "Chorus River"}, "description": {"en": "A swift violet river charges singing crystals and carries crystal fireflies along its banks."}},
		"visual": {"sky_color": "#201946", "daylight_tint": "#9df8e7"},
		"terrain": {"surface_content_id": "core.glass_tide_silt", "subsurface_content_id": "core.prismatic_basalt", "deep_content_id": "core.prismatic_basalt", "fluid_content_id": "core.chorus_brine"},
		"ecology": {"plant_content_ids": [], "creature_content_ids": ["core.creature.crystal_firefly"]},
		"environment": {"temperature": -0.08, "rain_multiplier": 0.0, "daylight_multiplier": 0.42},
		"placement": {"minimum_chunk_distance": 0, "introduction_chance": 1.0, "maximum_chunks_per_region": 8},
		"source_content_ids": ["core.chorus_brine", "core.chorus_crystal", "core.glass_tide_silt", "core.prismatic_basalt"],
	},
	"inverted_orchard": {
		"biome_id": "inverted_orchard", "kind": "biome", "schema_version": "1.0", "catalog_revision": 0,
		"display": {"name": {"en": "Inverted Orchard"}, "description": {"en": "Ancient trees grow downward from the cavern roof, bearing crystal fruit over an open forest floor."}},
		"visual": {"sky_color": "#2c1d38", "daylight_tint": "#e6b8e8"},
		"terrain": {"surface_content_id": "core.inverted_root", "subsurface_content_id": "core.prismatic_basalt", "deep_content_id": "core.prismatic_basalt", "fluid_content_id": null},
		"ecology": {"plant_content_ids": ["core.plant.cave_vines"], "creature_content_ids": ["core.creature.crystal_firefly"]},
		"environment": {"temperature": 0.08, "rain_multiplier": 0.0, "daylight_multiplier": 0.38},
		"placement": {"minimum_chunk_distance": 0, "introduction_chance": 1.0, "maximum_chunks_per_region": 8},
		"source_content_ids": ["core.inverted_root", "core.chorus_crystal", "core.prismatic_basalt"],
	},
	"bone_choir": {
		"biome_id": "bone_choir", "kind": "biome", "schema_version": "1.0", "catalog_revision": 0,
		"display": {"name": {"en": "Bone Choir"}, "description": {"en": "Titanic fossil ribs turn cavern drafts into song, while pressure vents launch travellers between ledges."}},
		"visual": {"sky_color": "#302a3a", "daylight_tint": "#ded4e4"},
		"terrain": {"surface_content_id": "core.prismatic_basalt", "subsurface_content_id": "core.choir_bone", "deep_content_id": "core.choir_bone", "fluid_content_id": null},
		"ecology": {"plant_content_ids": [], "creature_content_ids": ["core.creature.crystal_firefly"]},
		"environment": {"temperature": -0.18, "rain_multiplier": 0.0, "daylight_multiplier": 0.36},
		"placement": {"minimum_chunk_distance": 0, "introduction_chance": 1.0, "maximum_chunks_per_region": 8},
		"source_content_ids": ["core.choir_bone", "core.choir_vent", "core.prismatic_basalt"],
	},
	"shagot_lockworks": {
		"biome_id": "shagot_lockworks", "kind": "biome", "schema_version": "1.0", "catalog_revision": 0,
		"display": {"name": {"en": "Shagot Lockworks"}, "description": {"en": "Shagots maintain ancient sluices, Tideglass decks, and resonant gates across a captured underground river."}},
		"visual": {"sky_color": "#1d2438", "daylight_tint": "#a8eee0"},
		"terrain": {"surface_content_id": "core.resonance_bricks", "subsurface_content_id": "core.magnetic_stone", "deep_content_id": "core.magnetic_stone", "fluid_content_id": "core.chorus_brine"},
		"ecology": {"plant_content_ids": [], "creature_content_ids": ["core.creature.shagot_wanderer", "core.creature.shagot_guide", "core.creature.shagot_raider"]},
		"environment": {"temperature": 0.04, "rain_multiplier": 0.0, "daylight_multiplier": 0.4},
		"placement": {"minimum_chunk_distance": 0, "introduction_chance": 1.0, "maximum_chunks_per_region": 8},
		"source_content_ids": ["core.chorus_brine", "core.chorus_crystal", "core.tideglass", "core.resonance_bricks", "core.shagot_scaffold"],
	},
}

static func all() -> Dictionary:
	return SYSTEM.duplicate(true)
